### ISSUE TITLE
Trending Videos Broken

### ISSUE THREAD

**Issue by jkms** [TheBugLife/plugin.video.dtube#41]
```
                                            Error Contents: ('video',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.dtube/main.py", line 14, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.dtube/resources/lib/plugin.py", line 113, in run
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.dtube/resources/lib/plugin.py", line 93, in show_category
                                                videos = get_trending()
                                              File "/storage/.kodi/addons/plugin.video.dtube/resources/lib/plugin.py", line 33, in get_trending
                                                dtubeitem = {'name': viddata['post']['pending_payout_value'] + " | " + viddata['post']['json_metadata']['video']['info']['title'],
                                            KeyError: ('video',)
                                            -->End of Python script error report<--

```

Worked yesterday...

**Comment by jkms** [comment]
some of the trending posts for dtube weren't actually video posts, so the relevant json data was missing.

fixed here 02ef68e32c35309a3a6fcdb58cb4ac53616db7c8
